const OPEN_DIALOG = 'OPEN_DIALOG'
const FONTS_READY = 'FONTS_READY'
const WINDOW_READY = 'WINDOW_READY'
const LOAD_LIBRARY = 'LOAD_LIBRARY'
const LOAD_USERCONFIG = 'LOAD_USERCONFIG'
const IMPORT_BOOK = 'IMPORT_BOOK'
const START_IMPORT = 'START_IMPORT'
const READ_BOOK = 'READ_BOOK'
const LOAD_BOOK = 'LOAD_BOOK'

export {
  OPEN_DIALOG,
  WINDOW_READY,
  FONTS_READY,
  LOAD_LIBRARY,
  LOAD_USERCONFIG,
  IMPORT_BOOK,
  START_IMPORT,
  READ_BOOK,
  LOAD_BOOK,
}