const OPEN_DIALOG = 'OPEN_DIALOG'
const FONTS_READY = 'FONTS_READY'
const WINDOW_READY = 'WINDOW_READY'
const LOAD_LIBRARY = 'LOAD_LIBRARY'
const LOAD_USERCONFIG = 'LOAD_USERCONFIG'
const IMPORT_BOOK = 'IMPORT_BOOK'
const START_IMPORT = 'START_IMPORT'
const READ_BOOK = 'READ_BOOK'
const LOAD_BOOK = 'LOAD_BOOK'
const START_SEARCH = 'START_SEARCH'
const STOP_SEARCH = 'STOP_SEARCH'
const SEARCH_RESULT = 'SEARCH_RESULT'
const DELETE_BOOK = 'DELETE_BOOK'
const TOGGLE_FULLSCREEN = 'TOGGLE_FULLSCREEN'
const SAVE_LIBRARY = 'SAVE LIBRARY'
const SAVE_USERCONFIG = 'SAVE_USERCONFIG'

const CODE_OPEN_DEV_TOOLS = 'CODE_OPEN_DEV_TOOLS'

export {
  OPEN_DIALOG,
  WINDOW_READY,
  FONTS_READY,
  LOAD_LIBRARY,
  LOAD_USERCONFIG,
  IMPORT_BOOK,
  START_IMPORT,
  READ_BOOK,
  LOAD_BOOK,
  START_SEARCH,
  STOP_SEARCH,
  SEARCH_RESULT,
  DELETE_BOOK,
  TOGGLE_FULLSCREEN,
  SAVE_LIBRARY,
  SAVE_USERCONFIG,

  CODE_OPEN_DEV_TOOLS,
}